# Generated by Django 3.0.3 on 2020-02-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rango', '0003_auto_20200205_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=None),
        ),
    ]
